application: inprodsite
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /public
  static_dir: public

- url: /.*\.(x|ht)ml
  script: redirect.site

- url: /games/?.*
  script: games.site

- url: /admin/?.*
  script: admin.site

- url: /.*
  script: main.site
